### ISSUE TITLE
Upgrade for latest oauth2-client

### ISSUE THREAD

**Issue by ajibarra** [ipalaus/oauth2-pinterest#1]
Hi! The package was updated long time ago, I see it is not even in packagist. Do you still want to mantain the package or would you like to transfer ownership to me to upgrade it and keep it up to date with latest changes in oauth2-client package. I would also add a README where you will always be as an author of the project.

Let me know what do you think.

**Comment by ipalaus** [comment]
Hi @ajibarra, I don't use the package nowadays, so I'm not currently maintaining it. I'm more than happy for you to take over it. Would you rather like maintain it under your account? Thanks

**Comment by ajibarra** [comment]
Hi @ipalaus, yeah I would mantain it under my account because I am going to upgrade it and submit it to packagist, etc. Thank you!

**Comment by ajibarra** [comment]
Hi @ipalaus , I hope everything is okay. Please let me know if there is anything I need to do on my side to complete the process. Thank you!

**Comment by ipalaus** [comment]
All yours :)

**Comment by ajibarra** [comment]
@ipalaus Thank you :)
